apiVersion: v1
kind: ConfigMap
metadata:
  name: wf-frontend-configmap
  namespace: frontend
  labels:
    app: wf-frontend-configmap
data:
  appSettings.yaml: |
    # yaml file
    backend_url: http://api.weatherly.local
