apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-forecast-frontend_config-map
  namespace: frontend
  labels:
    app: weather-forecast-frontend_config-map
data:
  appSettings.yaml: |
    # yaml file
    backend_url: http://api.weatherly.local
