apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-weatherly-app
  namespace: argocd
  labels:
    workload: applications
spec:
  project: default
  source:
    repoURL: https://github.com/WellArchitectedLabs/WellArchitectedLab.MonoRepo.git
    targetRevision: feature/k8sWorkloadsMigration
    path: k8s/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  ignoreDifferences:
  - group: bitnami.com
    kind: SealedSecret
    jsonPointers:
    - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 2
      backoff:
        duration: 5s