apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
  namespace: argocd
  labels:
    isIstio: "true"
    workload: operations
  annotations:
    argocd.argoproj.io/sync-wave: "1"   # I need deamon to be installed after crds
spec:
  project: default
  source:
    chart: istiod
    repoURL: https://istio-release.storage.googleapis.com/charts
    targetRevision: "1.18.3"
    helm:
      values: |
        # Pilot (istiod) configuration
        pilot:
          # Node tolerations for weather-forecast nodepool
          tolerations:
            - key: workload
              operator: Equal
              value: weather-forecast
              effect: NoSchedule
          nodeSelector:
            kubernetes.azure.com/mode: system

          resources:
            requests:
              cpu: 50m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 512Mi
          
          # Sidecar injector webhook configuration
          sidecarInjectorWebhook:
            # Enable sidecar injection
            enableNamespacesByDefault: false
            # Rewrite app HTTP probes to work with sidecar
            rewriteAppHTTPProbe: true

        # Global configuration
        global:
          # Istio namespace
          istioNamespace: istio-system
          # Configure validation webhook
          configValidation: true
        
        meshConfig:
          # necessary for emitting tracing metrics for open telemetry collector
          enableTracing: true
          defaultProviders:
            tracing:
              - otel
          extensionProviders:
            - name: otel
              opentelemetry:
                service: otlp-collector-opentelemetry-collector.monitoring.svc.cluster.local
                port: 4317
          defaultConfig:
            tracing:
              # all requests are sent
              # use a lower percentage for production (10 per cent f.e)
              sampling: 100.0
          
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-system

  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istiod-default-validator
      jsonPointers:
        - /webhooks/*/clientConfig/caBundle
        
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m