pilot:
  replicaCount: 1
  resources:
    requests:
      cpu: 50m
      memory: 256Mi
    limits:
      cpu: 200m
      memory: 512Mi
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"

sidecarInjectorWebhook:
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"

validationWebhook:
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"

ingressGateway:
  enabled: true
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"

egressGateway:
  enabled: true
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
