pilot:
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - operations
sidecarInjectorWebhook:
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - operations
validationWebhook:
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - operations
ingressGateway:
  enabled: true
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - operations
egressGateway:
  enabled: true
  nodeSelector:
    workload: operations
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "operations"
      effect: "NoSchedule"
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
          - matchExpressions:
              - key: workload
                operator: In
                values:
                  - operations