apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: monitoring
  name: operations-kustomization

resources:
  - grafana/secrets.yaml
  - grafana/grafana-dashboards-backup.yaml
  - github/secrets.yaml