apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: frontend
  name: frontend-kustomization

resources:
  - namespace/frontend_namespace.yaml
  - deployment.yaml
  - high-availability/hpa.yaml
  - high-availability/pod-disruption-budget.yaml
  - services/service.yaml
  - services/virtual-service.yaml
  - config/config-map.yaml