apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: backend-kustomization

resources:
  - namespace/backend_namespace.yaml
  - backend_deployment.yaml
  - high-availability/backend_hpa.yaml
  - high-availability/backend_pod-disruption-budget.yaml
  - services/backend_service.yaml
  - services/backend_virtual-service.yaml