apiVersion: networking.istio.io/v1
kind: Gateway
metadata:
  name: weatherly-gateway
  namespace: istio-gateway
  labels:
    app: gateway
spec:
  selector:
    istio: ingressgateway
  servers:
  # weather api host gateway definition
  - port:
      number: 80
      name: http-weatherly-frontend
      protocol: HTTP
    hosts:
    - front.weatherly.local
  # weatherly frontend host gateway definition
  - port:
      number: 8080
      name: http-weatherly-backend 
      protocol: HTTP
    hosts:
    - api.weatherly.local
  