services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10
  insights-bff:
    build:
      context: ./bff
      dockerfile: Dockerfile
    container_name: insights-bff
    depends_on:
      - redis
    environment:
      WeatherForecast__Redis__ReadDbConnection: "redis:6379,abortConnect=false,connectTimeout=10000,syncTimeout=10000"
      WeatherForecast__Redis__WriteDbConnection: "redis:6379,abortConnect=false,connectTimeout=10000,syncTimeout=10000"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "5001:80"
    restart: always
    command: ["/app/wait-for.sh", "redis", "6379", "dotnet", "WeatherForecast.Api.dll"]
  insights-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - insights-bff
    environment:
      # Point frontend to backend container
      BACKEND_URL: "http://localhost:5001"
    container_name: insights-frontend
    ports:
      - "8080:80"
    restart: always