apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-azure-blob-imports
  namespace: backend
  labels:
    app: pvc-azure-blob-imports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual-blob-fuse
  volumeName: pv-azure-blob-imports