apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-az-blob-imports
  namespace: backend
  labels:
    app: pvc-az-blob-imports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: ""
  volumeName: pv-az-blob-imports