apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: az-blob-storage-imports
  namespace: backend
  labels:
    app: az-blob-storage-imports
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Mi
  storageClassName: dev-azureblob-fuse-msi