apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azure-blob-storage-imports
  namespace: backend
  labels:
    app: azure-blob-storage-imports
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      # requests 500 Megabytes
      storage: 500Mi
  volumeName: azure-blob-storage-imports
  # References the storage class defined in this same folder
  storageClassName: azureblob-fuse-msi