apiVersion: v1
kind: Service
metadata:
  name: heavy-traffic-generator
  namespace: frontend
spec:
  selector:
    app: heavy-traffic-generator
  ports:
  - name: http
    port: 8080
    targetPort: http