apiVersion: v1
kind: Service
metadata:
  name: heavy-traffic-generator
  namespace: frontend
  labels:
    app: heavy-traffic-generator
spec:
  selector:
    app: heavy-traffic-generator
  ports:
  - name: http
    port: 80
    targetPort: 80
