global:
  image:
    tag: ""   # let the chart decide

configs:
  params:
    server.insecure: true

server:
  replicas: 1
  service:
    type: ClusterIP

  nodeSelector:
    kubernetes.azure.com/mode: user
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "weather-forecast"
      effect: "NoSchedule"

controller:
  nodeSelector:
    kubernetes.azure.com/mode: user
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "weather-forecast"
      effect: "NoSchedule"

repoServer:
  nodeSelector:
    kubernetes.azure.com/mode: user
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "weather-forecast"
      effect: "NoSchedule"

applicationSet:
  nodeSelector:
    kubernetes.azure.com/mode: user
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "weather-forecast"
      effect: "NoSchedule"

redis:
  nodeSelector:
    kubernetes.azure.com/mode: user
  tolerations:
    - key: "workload"
      operator: "Equal"
      value: "weather-forecast"
      effect: "NoSchedule"
