apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: backend

helmCharts:
  - name: postgresql
    repo: https://charts.bitnami.com/bitnami
    version: 15.5.0
    releaseName: master-data
    namespace: backend
    valuesFile: values.yaml