---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: github-secrets
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_PAT: AgB9YZlsDPKOoXToW1k+kg3Ce0/PDIJObPJTYjOOAQ1fkQeOYHmnvfpK+vy3XKCx0OuK7GvL3Qv38+JJSbibNWWWGwtDLM+zmp6QlcwWKOD3CRqSLMdxZ4sy0npBFAfTuaXzt7TDtDJdIEqcr4grCVLp90GR2oILdjbZOwZobj/l1IFVwMPFFEQMYOidvZ0cFXbjxLAq4Ge1AHL4aiK3ECQPmbIfMJecnSUF6qlZG1KQ4Eo8lJ3EJAgnOEfXAv3RaWkzJJGiCTPVVju4h3NFNJQ0DVHc/2vcF6S4XFEp3k0SNmD3jWTsjSS+haESK681I/tZ0JFNaLpBAc+aEZA5G+LSsXezBeS0U+KjiBHCFo9l1p96ybkr1JIlG9SpZArsRW5+R4TxlIG3C2LXiX9Iiq8YkaOdh8WOanU22OBMr1v3Ba9Eby6+IEhHJ7OhFMaEUlVdnSmpUj/olUdxlKdAZxpKRmyQllBvelIDIY2xR9eHcqIEBPbZRqwmboGILPUvKAx/d4WqxNswjCbkQaH4TlGtblJ2bOAQ8UlcYwIAjBxenIguORBEawwdjmbW/hVkb+r6VAQ0becg10FhFiSAd6TYzcCQlLmp6FRvl/xDK24DveaMn+9mqS8MBZEX2uKNyQT0aTHeqTm6BDVKaJ3KVu62WBOWcTQOLw06KNDys3HXHMzc3cgeb1vh9wWyCadEWMyMVQii8yWEFa/lKsn0ui1/XrmQZGnpiVBGg3U+u/bmVc+M73ssf27XxFISDuiCQB47TlpeMzmGk0T14Mhj53zAFhuzIA+YJqIuizh8vHXxnm3VzeJDvAZRwPpuiuU=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: github-secrets
      namespace: monitoring
    type: Opaque
