---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  annotations:
    sealedsecrets.bitnami.com/namespace-wide: "true"
  name: github-secrets
  namespace: monitoring
spec:
  encryptedData:
    GITHUB_PAT: AgAUSE18JKIt4iw4VqyQg47G/JbnIfiI0Ouqr7L+yKhbJP9sUt0myF1lwVeyG2LlqgZVDgzOVd+U1A//1zu5xM0uIG3858CE0Yx3j97g6TV5zdKKN/4LZ0AUIDuJuZZc9Dry8Eq2UQCJ1kHCX8Ib8bkmfVv7MT2KJcLGd9yfnSt9QXRFxYvLp+dTgVsqsw7plWkp6pQaLwDtkXJIllcKK568DrLDLYQA7bGrR6pzbrL2MiVQqwQokokgrYz5f3cZ2WaCH1jXaW4OztU6SRkwxGEhM/4UPw+SbEprcW05EAIYul4SCGfRujV41y+/wRQZ0rFQ1QAy/Q2jKvvfu/Acs/E8BEvYUdoipZeKU5LPwVknDaRtpdnnqPMiDHCVSA0jdz+vmNHnxIafCFQZYIgyPqgkeEPJrrgrrJFfFFaQKRbusexvPr8eaYxT82WMFrqtFGPmH7KoWXCEMLx0+6mEQ42MjVEZTWkE0IP1k0jP+3iwcd9BO10c8yeEN/gOHEpXswJpM+7UwIiepINo8FR8E2ZON0bBxhA6tlwCOa3w7BqfIdzEjJioqoyKNGckvHdixPbcTiSCw2CHED6ThvSUzUkx6gwFPZZ62A7Z2N9wl/6li7r4P2p48Scs/o0lHVR4UWVCqd8YMwLsM3kttRnkd/ACcBxWvO+5ZREAmzdjHMqGeSs/iHmh8SuUwuGLu8FfrIIb97i2nnGZM5v1zcB16CPziysc7tgZf1xR/d/ws2aNAQy8B8ushxsMSiFfNDTNQtivcArz+uOIjosNV+MiEi2CGXmCq2Xw0dDislNvOeZhD9bxWNXxBhhw8JCBhiA=
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/namespace-wide: "true"
      name: github-secrets
      namespace: monitoring
    type: Opaque
