# This is a cluster IP service that load balances between the three redis pods
apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-bff-redis-secondary
  namespace: backend
  labels:
    app: weather-forecast-bff-redis
    version: v1
spec:
  type: ClusterIP
  selector:
    app: weather-forecast-bff-redis
  ports:
  - name: redis
    port: 6379
