apiVersion: v1
kind: Service
metadata:
  name: insights-bff-service
  namespace: backend
spec:
  selector:
    app: insights-bff
    version: v1
  ports:
  - name: http
    port: 8080
    targetPort: 80