apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: insights-bff-virtualservice
  namespace: istio-gateway
  labels:
    app: backend
    version: v1
spec:
  hosts:
    - api.weatherly.local
  gateways:
    - istio-gateway/dev-weatherly-gateway
  http:
    - match:
        - uri:
            prefix: /
      route:
        - destination:
            host: dev-insights-bff-service.backend.svc.cluster.local
            port:
              number: 8080
