apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: database-kustomization

resources:
  - stateful-set.yaml
  - services/write-service.yaml
  - services/read-service.yaml
  - services/headless-service.yaml