apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: frontend
  name: frontend-kustomization

resources:
  - namespace/backend_namespace.yaml
  - frontend_deployment.yaml
  - high-availability/frontend_hpa.yaml
  - high-availability/frontend_pod-disruption-budget.yaml
  - gateway-api/frontend_service.yaml
  - gateway-api/frontend_reference-grant.yaml
  - gateway-api/frontend_virtual-service.yaml
  - config/frontend_config-map.yaml

configurations:
  - kustomizeconfig.yaml