apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# reference all manifests from base folder
resources:
  - ../../manifests/operations
  - ../../manifests/insights/bff
  - ../../manifests/insights/frontend
  - ../../manifests/shared
  - ../../manifests/insights/database
  - insights-bff_config-map.yaml
  - ../../manifests/tools/htg

# define a sandbox prefix for all created environment in relation to this overlay
namePrefix: sandbox-
# no suffix is defined
nameSuffix: ""

# adds a metadata.label for every resource created by this kustomize hop
# this allows easy resource managemnt using -l filters
commonLabels:
  environment: sandbox

# we need to track the environment in order to use it on pod level
# config map generators are used here in order to update the pods as the config changes
# this will created a config which is suffixed by the hash of the config content. Something like 
configMapGenerator:
  - name: rediswfconfigenvvars
    namespace: backend
    literals:
      # used by redis in order to configure the replication mecanism
      - REDIS_HEADLESS_SERVICE=sandbox-insights-bff-redis
    # this is necessary in order to avoid non conventional resource name with naming RFCs
    options:
      disableNameSuffixHash: true

# # section for applying all patches
# # patches are applied in this particular case since HTTPRoute and Gateway API resources are a bit trailing (at least at the moment of the implementation)
# # in termsof kustomization management. These resources relatively new compared to ingress and do not fully manage prefix propagation to their referenced resources by kubectl -k
# patches:
#   - target:
#       group: gateway.networking.k8s.io
#       version: v1
#       kind: HTTPRoute
#       name: frontend-httproute
#       namespace: istio-gateway
#     # path to frontend http route to service patch file
#     path: patches/patch-frontend-httproute.yaml
#   - target:
#       group: gateway.networking.k8s.io
#       version: v1
#       kind: HTTPRoute
#       name: backend-httproute
#       namespace: istio-gateway
#     # path to backend http route to service patch file
#     path: patches/patch-backend-httproute.yaml