apiVersion: v1
kind: Service
metadata:
  name: weather-forecast-bff-service
  namespace: backend
spec:
  selector:
    app: weather-forecast-bff
    version: v1
  ports:
  - name: http
    port: 8080
    targetPort: 80