apiVersion: v1
kind: ConfigMap
metadata:
  name: insights-frontend-configmap
  namespace: frontend
  labels:
    app: insights-frontend-configmap
data:
  appSettings.yaml: |
    # yaml file
    backend_url: http://api.weatherly.local
