apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: master-data-staging-kustomization
resources:
  - job/cities-import6.yaml
  - pv/imports-sa_pv1.yaml
  - pvc/imports-storage_claim1.yaml