apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: master-data-staging-kustomization
resources:
  - job/cities-import.yaml
  - storage-class/imports_storage-account.yaml
  - pvc/staging-imports-storage_claim.yaml