apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: master-data-staging-kustomization
resources:
  - job/cities-import2.yaml
  - storage-class/imports_stoclass.yaml
  - pvc/imports-storage_claim.yaml