apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  namespace: backend
  name: master-data-staging-kustomization
resources:
  - jobs/cities-import.yaml
  - pvs/imports_storage-account.yaml
  - pvcs/imports_storage-claim.yaml