apiVersion: v1
kind: Service
metadata:
  name: insights-frontend-service
  namespace: frontend
spec:
  selector:
    app: insights-frontend
    version: v1
  ports:
  - name: http
    port: 80
    targetPort: 80