apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-az-blob-imports
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  csi:
    driver: blob.csi.azure.com
    volumeHandle: stwfimportsdev_imports        # unique handle
    volumeAttributes:
      storageAccount: stwfimportsdev           # your storage account
      containerName: imports                    # blob container
      resourceGroup: rg-kubernetes-dev-001     # RG
      protocol: fuse                            # must be fuse