apiVersion: v1
kind: ConfigMap
metadata:
  name: weather-forecast-bff-configmap
  namespace: backend
data:
  appsettings.json: |
    {
    "Logging": {
      "LogLevel": {
        "Default": "Information",
        "Microsoft.AspNetCore": "Warning"
      }
    },
    "AllowedHosts": "*",
    "WeatherForecast": {
        "Redis": {
          "WriteDbConnection": "dev-weather-forecast-bff-redis-primary.backend.svc.cluster.local:6379",
          "ReadDbConnection": "dev-weather-forecast-bff-redis-secondary.backend.svc.cluster.local:6379"
        }
      }
    }