name: Status Check - Insights Frontend Pull Request Build Check

on:
    pull_request:
      branches:
          - main
          - develop
          - 'release/**'
      paths:
        - src/insights/frontend/**
    workflow_dispatch:  # allows manual testing

jobs:
  frontend-buildCheck:
    name: Frontend Status Check - Try package docker image
    uses: ./.github/workflows/template_ci.yml
    with:
      service_name: insights-frontend
      service_path: src/insights/frontend/
      gitversion_config_path: src/insights/frontend//GitVersion.yml
      #status check doesn't push into ACR
      push_to_registry: false
    secrets:
      ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
      ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
      ACR_PASSWORD: ${{ secrets.ACR_PASSWORD }}
