name: Status Check - Insights Bff Pull Request Build

on:
    pull_request:
        branches:
          - develop
          - main
          - 'release/**'
        paths:
          - src/insights/bff/**
    workflow_dispatch:  # allows manual testing

jobs:

  # build check
  backend-buildCheck:
    uses: ./.github/workflows/template_ci.yml
    name: Insights Bff Status Check - Try package docker image
    with:
        service_name: insights-bff
        gitversion_config_path: src/insights/bff/GitVersion.yml
        #status check doesn't push into ACR
        push_to_registry: false
        service_path: src/insights/bff
    secrets:
        ACR_LOGIN_SERVER: ${{ secrets.ACR_LOGIN_SERVER }}
        ACR_PASSWORD : ${{ secrets.ACR_PASSWORD }}
        ACR_USERNAME: ${{ secrets.ACR_USERNAME }}
        
  # coverage check
  run-UnitTests:
      uses: ./.github/workflows/template_codecov-dotnet.yml
      name: Insights Bff Status Check - Tests & Coverage
      with:
        test_project_folder: src/insights/bff/Tests
      secrets:
        codecov_token: ${{ secrets.CODECOV_TOKEN }}